start D:\Anaconda\envs\hy\python.exe king_restful.py --port 5000
start D:\Anaconda\envs\hy\python.exe king_restful.py --port 5001
start D:\Anaconda\envs\hy\python.exe king_restful.py --port 5002
start D:\Anaconda\envs\hy\python.exe king_restful.py --port 5003
start D:\Anaconda\envs\hy\python.exe king_restful.py --port 5004
start D:\Anaconda\envs\hy\python.exe king_restful.py --port 5005
start D:\Anaconda\envs\hy\python.exe king_restful.py --port 5006
start D:\Anaconda\envs\hy\python.exe king_restful.py --port 5007
start D:\Anaconda\envs\hy\python.exe king_restful.py --port 5008
start D:\Anaconda\envs\hy\python.exe king_restful.py --port 5009
start D:\Anaconda\envs\hy\python.exe king_restful.py --port 5010
start D:\Anaconda\envs\hy\python.exe king_restful.py --port 5011
start D:\Anaconda\envs\hy\python.exe king_restful.py --port 5012
start D:\Anaconda\envs\hy\python.exe king_restful.py --port 5013
start D:\Anaconda\envs\hy\python.exe king_restful.py --port 5014
start D:\Anaconda\envs\hy\python.exe king_restful.py --port 5015
start D:\Anaconda\envs\hy\python.exe king_restful.py --port 5016
start D:\Anaconda\envs\hy\python.exe king_restful.py --port 5017
start D:\Anaconda\envs\hy\python.exe king_restful.py --port 5018
start D:\Anaconda\envs\hy\python.exe king_restful.py --port 5019